# GitHub-Actions() -> VM(Bash || PowerShell)
---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      working-directory: "."
      shell: bash
      run: bash make.sh ci
